language: node_js
install:
  - sh ./script/install.sh

branches:
  only:
  - master

jobs:
  include:
    - stage: test
      script: sh ./script/test.sh
    - stage: release
      script: sh ./script/release.sh
