language: node_js
install:
  - npm install

branches:
  only:
  - master

jobs:
  include:
    - stage: test
      script: sh ./script/test.sh
    - stage: release
      script:
        - npm run release
