language: node_js
node:
  - lts/*

install:
  - npm install

branches:
  only:
  - master

jobs:
  include:
    - stage: test
      script:
        - echo "testing"
    - stage: release
      script:
        - npm run release
