language: node_js
install:
  - sh ./script/install.sh

branches:
  only:
  - master

jobs:
  include:
    - stage: test
      script: echo 'testing'
    - stage: deploy
      script: echo 'deploying'
